// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJePh2eeHeatYsIeZslS4_-y9456gG6ZY',
    appId: '1:735993325759:web:8884ef31f8b5f86b5e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    authDomain: 'fir-demo-74267.firebaseapp.com',
    storageBucket: 'fir-demo-74267.appspot.com',
    measurementId: 'G-46KRMKGTS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM1oALqVdy_Um9VUQz177EYILK7-s-Sg0',
    appId: '1:735993325759:android:665817d5845d2e5f5e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    storageBucket: 'fir-demo-74267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiUmgfveFfBhcoe1-_EEZjF01zjzyqRdg',
    appId: '1:735993325759:ios:5e4097044d63b0885e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    storageBucket: 'fir-demo-74267.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiUmgfveFfBhcoe1-_EEZjF01zjzyqRdg',
    appId: '1:735993325759:ios:5e4097044d63b0885e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    storageBucket: 'fir-demo-74267.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJePh2eeHeatYsIeZslS4_-y9456gG6ZY',
    appId: '1:735993325759:web:f0001d10af8383fb5e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    authDomain: 'fir-demo-74267.firebaseapp.com',
    storageBucket: 'fir-demo-74267.appspot.com',
    measurementId: 'G-CV56NDMTBR',
  );
}
